ZealEducationManager/Controllers/BatchesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZealEducationManager.Entities;
using ZealEducationManager.Models.BatchViewModels;
using ZealEducationManager.Models.CandidatesViewModels;

namespace ZealEducationManager.Controllers
{
    [Authorize]
    public class BatchesController : Controller
    {
        private readonly ZealEducationManagerContext _context;

        public BatchesController(ZealEducationManagerContext context)
        {
            _context = context;
        }

        // GET: Batches
        [Route("batches/all-batches")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Batches.ToListAsync());
		}
		[Route("batches/batch-details")]
		public async Task<IActionResult> ListCandidate(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var batch = await _context.Batches
                .FirstOrDefaultAsync(m => m.BatchId == id);
            if (batch == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            var listCandidate = await _context.Candidates.Where(c => c.BatchId == batch.BatchId).ToListAsync();
            ViewData["BatchCode"] = batch.BatchCode;
            return View(listCandidate);

        }
        // GET: Batches/Create
        [Route("batches/add-batch")]
        public async Task<IActionResult> Create()
        {
            return View();
        }


        // POST: Batches/Create
        [Route("batches/add-batch")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddBatchViewModel batch)
        {
            if (ModelState.IsValid)
            {
                var existBatchCode = _context.Batches.FirstOrDefault(c => c.BatchCode == batch.BatchCode);
                if (existBatchCode != null)
                {
                    ModelState.AddModelError("BatchCode", "Batch Code has already existed"); 
                    return View(batch);
                }
                if (batch.StartDate > batch.EndDate)
                {
                    ModelState.AddModelError("EndDate", "The start date must be earlier than the end date");
                    return View(batch);
                }
                var newBatch = new Batch { 
                    BatchCode = batch.BatchCode,
                    StartDate = batch.StartDate,
                    EndDate = batch.EndDate
                };
                _context.Add(newBatch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(batch);
        }

        // GET: Batches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var batch = await _context.Batches.FindAsync(id);
            if (batch == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            AddBatchViewModel modelView = new AddBatchViewModel
            {
                BatchId = batch.BatchId,
                BatchCode = batch.BatchCode,
                StartDate = batch.StartDate,
                EndDate = batch.EndDate
            };
            return View(modelView);
        }

        // POST: Batches/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BatchId,BatchCode,StartDate,EndDate")] AddBatchViewModel batch)
        {
            if (id != batch.BatchId)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    var existBatchCode = _context.Batches
                        .Where(c => c.BatchCode == batch.BatchCode && c.BatchId != batch.BatchId).FirstOrDefault();
                    if (existBatchCode != null)
                    {
                        ModelState.AddModelError("BatchCode", "Batch Code has already existed");
                        return View(batch);
                    }
                    if (batch.StartDate > batch.EndDate)
                    {
                        ModelState.AddModelError("EndDate", "The start date must be earlier than the end date");
                        return View(batch);
                    }
                    var updatedBatch = _context.Batches
                        .Where(c => c.BatchId == batch.BatchId).FirstOrDefault();
                    if (updatedBatch != null)
                    {
                        updatedBatch.BatchCode = batch.BatchCode;
                        updatedBatch.StartDate = batch.StartDate;
                        updatedBatch.EndDate = batch.EndDate;
                        _context.Update(updatedBatch);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BatchExists(batch.BatchId))
                    {
                        TempData["message"] = "Cannot find any data";
                        return RedirectToAction("Message", "Dashboard");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(batch);
        }

        // GET: Batches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var batch = await _context.Batches
                .FirstOrDefaultAsync(m => m.BatchId == id);
            if (batch == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            return View(batch);
        }

        // POST: Batches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        { try
            {
				var batch = await _context.Batches.FindAsync(id);
				if (batch != null)
				{
					_context.Batches.Remove(batch);
				}

				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			} catch
            {
                TempData["message"] = "Cannot Delete this Record";
                return RedirectToAction("Message","Dashboard");
            }

            
        }

        private bool BatchExists(int id)
        {
            return _context.Batches.Any(e => e.BatchId == id);
        }
    }
}

ZealEducationManager/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.Pkcs;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using ZealEducationManager.Entities;
using ZealEducationManager.Models.CandidatesViewModels;
using static System.Net.Mime.MediaTypeNames;

namespace ZealEducationManager.Controllers
{
    [Authorize]
    public class CandidatesController : Controller
    {
        private readonly ZealEducationManagerContext _context;

        public CandidatesController(ZealEducationManagerContext context)
        {
            _context = context;
        }

        // GET: Candidates
        public async Task<IActionResult> Index()
        {
            return View(await _context.Candidates.Include(c => c.Batch).ToListAsync());
        }

        // GET: Candidates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var candidate = await _context.Candidates.Include(c => c.Batch)
                .FirstOrDefaultAsync(m => m.CandidateId == id);
            if (candidate == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            return View(candidate);
        }

        // GET: Candidates/Create
        public IActionResult Create()
        {
			var viewModel = new AddCandidateView
			{
				BatchCode = _context.Batches.Select(c => new SelectListItem
				{
					Value = c.BatchId.ToString(),
					Text = c.BatchCode
				})
			};
			return View(viewModel);
        }

        // POST: Candidates/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCandidateView viewodel )
        {
            if (ModelState.IsValid)
            {
                var dob = viewodel.DateOfBirth.ToDateTime(TimeOnly.MinValue);
                if (dob >= DateTime.Today)
                {
                    ModelState.AddModelError("DateOfBirth", "The Date Of Birth must be earlier than today"); viewodel.BatchCode = _context.Batches.Select(c => new SelectListItem
                    {
                        Value = c.BatchId.ToString(),
                        Text = c.BatchCode
                    });
                    return View(viewodel);
                }
                if (viewodel.DateOfBirth >= viewodel.DateOfJoining)
                {
                    ModelState.AddModelError("DateOfJoining", "The Date Of Joining must be later than the Date of Birth");
                    viewodel.BatchCode = _context.Batches.Select(c => new SelectListItem
                    {
                        Value = c.BatchId.ToString(),
                        Text = c.BatchCode
                    });
                    return View(viewodel);
                }
                var candidate = new Candidate
                {
                    FirstName = viewodel.FirstName,
                    LastName = viewodel.LastName,
                    DateOfBirth = viewodel.DateOfBirth,
                    DateOfJoining = viewodel.DateOfJoining,
                    ContactInfo = viewodel.ContactInfo,
                    OutstandingFee = viewodel.OutstandingFee,
                    Status = viewodel.Status,
                    BatchId = viewodel.BatchId,
                };
                _context.Add(candidate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            viewodel.BatchCode = _context.Batches.Select(c => new SelectListItem
            {
                Value = c.BatchId.ToString(),
                Text = c.BatchCode
            });
            return View(viewodel);
        }

        // GET: Candidates/Edit/5
        [Route("candidates/edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            var candidate = await _context.Candidates.FindAsync(id);
            if (candidate == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var viewModel = new EditCandidateView
            {
                CandidateId = candidate.CandidateId,
                FirstName = candidate.FirstName,
                LastName = candidate.LastName,
                DateOfBirth = candidate.DateOfBirth,
                DateOfJoining = candidate.DateOfJoining,
                ContactInfo = candidate.ContactInfo,
                OutstandingFee = candidate.OutstandingFee,
                Status = candidate.Status,
                BatchId = candidate.BatchId,
                BatchCode = _context.Batches.Select(c => new SelectListItem
                {
                    Value = c.BatchId.ToString(),
                    Text = c.BatchCode
                })
            };
            return View(viewModel);
        }

        // POST: Candidates/Edit/5
        [Route("candidates/edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CandidateId,FirstName,LastName,DateOfBirth,DateOfJoining,ContactInfo,OutstandingFee,Status,BatchId")] EditCandidateView viewmodel)
        {
            if (id != viewmodel.CandidateId)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var dob = viewmodel.DateOfBirth.ToDateTime(TimeOnly.MinValue);
                    if (dob >= DateTime.Today)
                    {
                        ModelState.AddModelError("DateOfBirth", "The Date Of Birth must be earlier than today"); viewmodel.BatchCode = _context.Batches.Select(c => new SelectListItem
                        {
                            Value = c.BatchId.ToString(),
                            Text = c.BatchCode
                        });
                        return View(viewmodel);
                    }
                    if (viewmodel.DateOfBirth >= viewmodel.DateOfJoining)
                    {
                        ModelState.AddModelError("DateOfJoining", "The Date Of Joining must be later than the Date of Birth");
                        viewmodel.BatchCode = _context.Batches.Select(c => new SelectListItem
                        {
                            Value = c.BatchId.ToString(),
                            Text = c.BatchCode
                        });
                        return View(viewmodel);
                    }
                    var candidate = await _context.Candidates.FindAsync(viewmodel.CandidateId);
                    candidate.FirstName = viewmodel.FirstName;
                    candidate.LastName = viewmodel.LastName;
                    candidate.DateOfBirth = viewmodel.DateOfBirth;
                    candidate.DateOfJoining = viewmodel.DateOfJoining;
                    candidate.ContactInfo = viewmodel.ContactInfo;
                    candidate.OutstandingFee = viewmodel.OutstandingFee;
                    candidate.Status = viewmodel.Status;
                    candidate.BatchId = viewmodel.BatchId;
                    _context.Update(candidate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidateExists(viewmodel.CandidateId))
                    {
                        TempData["message"] = "Cannot find any data";
                        return RedirectToAction("Message", "Dashboard");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //Else (ModelState Is Invalid
            viewmodel.BatchCode = _context.Batches.Select(c => new SelectListItem
            {
                Value = c.BatchId.ToString(),
                Text = c.BatchCode
            });
            return View(viewmodel);
        }

        // GET: Candidates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var candidate = await _context.Candidates
                .FirstOrDefaultAsync(m => m.CandidateId == id);
            if (candidate == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var candidate = await _context.Candidates.FindAsync(id);
                if (candidate != null)
                {
                    _context.Candidates.Remove(candidate);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["message"] = "Cannot Delete this Record";

ZealEducationManager/Views/Batches/Create.cshtml
@model ZealEducationManager.Models.BatchViewModels.AddBatchViewModel

@{
    ViewData["Title"] = "Add Batch";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<div class="page-header">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <h5 class="text-uppercase mb-0 mt-0 page-title">Add Batch</h5>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BatchCode" class="control-label"></label>
                <input asp-for="BatchCode" class="form-control" />
                <span asp-validation-for="BatchCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input type="date" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input type="date" asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-secondary" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

ZealEducationManager/Views/Batches/Delete.cshtml
@model ZealEducationManager.Entities.Batch

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Batch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BatchCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BatchCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BatchId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ZealEducationManager/Views/Batches/Edit.cshtml
@model ZealEducationManager.Models.BatchViewModels.AddBatchViewModel

@{
    ViewData["Title"] = "Edit Batch";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<div class="page-header">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <h5 class="text-uppercase mb-0 mt-0 page-title">Edit Batch</h5>
        </div>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BatchId" />
            <div class="form-group">
                <label asp-for="BatchCode" class="control-label"></label>
                <input asp-for="BatchCode" class="form-control" />
                <span asp-validation-for="BatchCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input type="date" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input type="date" asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ZealEducationManager/Views/Batches/Index.cshtml
@model IEnumerable<ZealEducationManager.Entities.Batch>

@{
    ViewData["Title"] = "Batches";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}



<div class="page-header">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-12">
			<h5 class="text-uppercase mb-0 mt-0 page-title">Batches</h5>
		</div>
	</div>
</div>
<div class="content-page">
	<div class="row">
		<div class="col-sm-5 col-12">
		</div>
		<div class="col-sm-7 col-12 text-right add-btn-col">
			<a asp-action="Create" class="btn btn-primary btn-rounded" >
				<i class="fas fa-plus"></i> Add New Batch
			</a>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12 mb-3">
			<div class="table-responsive">
				<table class="table custom-table mb-0 datatable">
					<thead class="thead-light">
						<tr>
							<th>Batch Code </th>
							<th>Start Date</th>
							<th>End Date</th>
							<th class="text-right">Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							<tr class="Batch-completed">
								<td>
									@Html.DisplayFor(modelItem => item.BatchCode)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.StartDate)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.EndDate)
								</td>
								<td class="text-right">
									<div class="dropdown dropdown-action">
										<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
										   aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
										<div class="dropdown-menu dropdown-menu-right">
											<a class="dropdown-item" asp-action="ListCandidate" asp-route-id="@item.BatchId" title="Detail">
												<i class="fas fa-book m-r-5"></i> List Candidates
											</a>
											<a class="dropdown-item" asp-action="Edit" asp-route-id="@item.BatchId"  title="Edit">
												<i class="fas fa-pencil-alt m-r-5"></i> Edit
											</a>
											<a class="dropdown-item" asp-action="Delete" asp-route-id="@item.BatchId"  title="Delete">
												<i class="fas fa-trash-alt m-r-5"></i> Delete
											</a>
										</div>
									</div>
								</td>
							</tr>
						}

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

ZealEducationManager/Views/Batches/ListCandidate.cshtml
@model IEnumerable<ZealEducationManager.Entities.Candidate>

@{
    ViewData["Title"] = "Batch Details";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    var batchCode = ViewData["BatchCode"];
}

<h1>Candidates In Batch @batchCode</h1>

<table class="table datatable">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                Contact Info
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CandidateId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactInfo)
                </td>
                <td>
                    <a asp-controller="Candidates" asp-action="Details" asp-route-id="@item.CandidateId" >View Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row">
    <a class="btn btn-secondary" href="javascript:history.back()">Back</a>
</div>