ZealEducationManager/Entities/Report.cs
using System;
using System.Collections.Generic;

namespace ZealEducationManager.Entities;

public partial class Report
{
    public int ReportId { get; set; }

    public string ReportType { get; set; } = null!;

    public DateOnly GeneratedDate { get; set; }
}

ZealEducationManager/Controllers/BatchesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZealEducationManager.Entities;
using ZealEducationManager.Models.BatchViewModels;
using ZealEducationManager.Models.CandidatesViewModels;

namespace ZealEducationManager.Controllers
{
    [Authorize]
    public class BatchesController : Controller
    {
        private readonly ZealEducationManagerContext _context;

        public BatchesController(ZealEducationManagerContext context)
        {
            _context = context;
        }

        // GET: Batches
        [Route("batches/all-batches")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Batches.ToListAsync());
		}
		[Route("batches/batch-details")]
		public async Task<IActionResult> ListCandidate(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var batch = await _context.Batches
                .FirstOrDefaultAsync(m => m.BatchId == id);
            if (batch == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            var listCandidate = await _context.Candidates.Where(c => c.BatchId == batch.BatchId).ToListAsync();
            ViewData["BatchCode"] = batch.BatchCode;
            return View(listCandidate);

        }
        // GET: Batches/Create
        [Route("batches/add-batch")]
        public async Task<IActionResult> Create()
        {
            return View();
        }


        // POST: Batches/Create
        [Route("batches/add-batch")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddBatchViewModel batch)
        {
            if (ModelState.IsValid)
            {
                var existBatchCode = _context.Batches.FirstOrDefault(c => c.BatchCode == batch.BatchCode);
                if (existBatchCode != null)
                {
                    ModelState.AddModelError("BatchCode", "Batch Code has already existed"); 
                    return View(batch);
                }
                if (batch.StartDate > batch.EndDate)
                {
                    ModelState.AddModelError("EndDate", "The start date must be earlier than the end date");
                    return View(batch);
                }
                var newBatch = new Batch { 
                    BatchCode = batch.BatchCode,
                    StartDate = batch.StartDate,
                    EndDate = batch.EndDate
                };
                _context.Add(newBatch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(batch);
        }

        // GET: Batches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var batch = await _context.Batches.FindAsync(id);
            if (batch == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            AddBatchViewModel modelView = new AddBatchViewModel
            {
                BatchId = batch.BatchId,
                BatchCode = batch.BatchCode,
                StartDate = batch.StartDate,
                EndDate = batch.EndDate
            };
            return View(modelView);
        }

        // POST: Batches/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BatchId,BatchCode,StartDate,EndDate")] AddBatchViewModel batch)
        {
            if (id != batch.BatchId)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    var existBatchCode = _context.Batches
                        .Where(c => c.BatchCode == batch.BatchCode && c.BatchId != batch.BatchId).FirstOrDefault();
                    if (existBatchCode != null)
                    {
                        ModelState.AddModelError("BatchCode", "Batch Code has already existed");
                        return View(batch);
                    }
                    if (batch.StartDate > batch.EndDate)
                    {
                        ModelState.AddModelError("EndDate", "The start date must be earlier than the end date");
                        return View(batch);
                    }
                    var updatedBatch = _context.Batches
                        .Where(c => c.BatchId == batch.BatchId).FirstOrDefault();
                    if (updatedBatch != null)
                    {
                        updatedBatch.BatchCode = batch.BatchCode;
                        updatedBatch.StartDate = batch.StartDate;
                        updatedBatch.EndDate = batch.EndDate;
                        _context.Update(updatedBatch);
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BatchExists(batch.BatchId))
                    {
                        TempData["message"] = "Cannot find any data";
                        return RedirectToAction("Message", "Dashboard");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(batch);
        }

        // GET: Batches/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var batch = await _context.Batches
                .FirstOrDefaultAsync(m => m.BatchId == id);
            if (batch == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            return View(batch);
        }

        // POST: Batches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        { try
            {
				var batch = await _context.Batches.FindAsync(id);
				if (batch != null)
				{
					_context.Batches.Remove(batch);
				}

				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			} catch
            {
                TempData["message"] = "Cannot Delete this Record";
                return RedirectToAction("Message","Dashboard");
            }

            
        }

        private bool BatchExists(int id)
        {
            return _context.Batches.Any(e => e.BatchId == id);
        }
    }
}

ZealEducationManager/Controllers/ExamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ZealEducationManager.Entities;
using ZealEducationManager.Models.CandidatesViewModels;
using ZealEducationManager.Models.ExamsViewModel;

namespace ZealEducationManager.Controllers
{
    [Authorize]
    public class ExamsController : Controller
    {
        private readonly ZealEducationManagerContext _context;

        public ExamsController(ZealEducationManagerContext context)
        {
            _context = context;
        }

        // GET: Exams
        public async Task<IActionResult> Index()
        {
            var zealEducationManagerContext = _context.Exams.Include(e => e.Batch).Include(e => e.Course);
            return View(await zealEducationManagerContext.ToListAsync());
        }

        // GET: Exams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var exam = await _context.Exams
                .Include(e => e.Batch)
                .Include(e => e.Course)
                .FirstOrDefaultAsync(m => m.ExamId == id);
            if (exam == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            return View(exam);
        }


		// GET: Exams/Create
		public IActionResult Create()
        {
            var viewModel = new AddExamModel
            {
                CourseCode = _context.Courses.Select(c => new SelectListItem
                {
                    Value = c.CourseId.ToString(),
                    Text = c.CourseCode
                }),
				BatchCode = _context.Batches.Select(b => new SelectListItem
				{
					Value = b.BatchId.ToString(),
					Text = b.BatchCode
				})
			};
			return View(viewModel);
        }

        // POST: Exams/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddExamModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var batch = _context.Batches.Where(b => b.BatchId == viewModel.BatchId).FirstOrDefault();
                var examdate = viewModel.ExamDate.ToDateTime(TimeOnly.MinValue);
                var startdate = batch.StartDate.ToDateTime(TimeOnly.MinValue);
                var enddate = batch.EndDate.ToDateTime(TimeOnly.MinValue);
                if (examdate < startdate || examdate > enddate)
                {
                    ModelState.AddModelError("ExamDate", "The Exam Date must be in dates range of Batch");
                    viewModel.CourseCode = _context.Courses.Select(c => new SelectListItem
                    {
                        Value = c.CourseId.ToString(),
                        Text = c.CourseCode
                    });
                    viewModel.BatchCode = _context.Batches.Select(b => new SelectListItem
                    {
                        Value = b.BatchId.ToString(),
                        Text = b.BatchCode
                    });
                    return View(viewModel);
                }
                var exam = new Exam
                {
                    ExamId = viewModel.ExamId,
                    ExamDate = viewModel.ExamDate,
                    CourseId = viewModel.CourseId,
                    BatchId = viewModel.BatchId,
                };
                _context.Add(exam);
                await _context.SaveChangesAsync();
                // Get all candidates in the batch
                var candidates = await _context.Candidates
                    .Where(c => c.BatchId == exam.BatchId)
                    .ToListAsync();

                // Create ExamResult records for each candidate
                foreach (var candidate in candidates)
                {
                    var examResult = new ExamResult
                    {
                        ExamId = exam.ExamId,
                        CandidateId = candidate.CandidateId
                        // MarkObtained is left null as per requirement
                    };
                    _context.ExamResults.Add(examResult);
                }

                // Save all changes to the database
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            viewModel.CourseCode = _context.Courses.Select(c => new SelectListItem
            {
                Value = c.CourseId.ToString(),
                Text = c.CourseCode
            });
            viewModel.BatchCode = _context.Batches.Select(b => new SelectListItem
            {
                Value = b.BatchId.ToString(),
                Text = b.BatchCode
            });
            return View(viewModel);
        }


        // View Candidates in Exam

        public async Task<IActionResult> ListCandidate(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }

            var exam = await _context.Exams.Include(e => e.Batch).Include(e => e.Course)
                .FirstOrDefaultAsync(m => m.ExamId == id);
            if (exam == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            var listCandidate = await _context.ExamResults.Include(e => e.Candidate)
                .Where(c => c.ExamId == exam.ExamId).ToListAsync();
            ViewData["ExamId"] = exam.ExamId;
            ViewData["CourseCode"] = exam.Course.CourseCode;
            ViewData["BatchCode"] = exam.Batch.BatchCode;
            return View(listCandidate);
        }

        // View For Input Mark
        public async Task<IActionResult> InputMarks(int? id)
        {
            if (id == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            var examresult = await _context.ExamResults.Where(er => er.ResultId == id).Include(er => er.Candidate).FirstOrDefaultAsync();
            if (examresult == null)
            {
                TempData["message"] = "Cannot find any data";
                return RedirectToAction("Message", "Dashboard");
            }
            var viewModel = new InputMarkViewModel
            {
                ResultId = examresult.ResultId,
                CandidateId = examresult.CandidateId,
                ExamId = examresult.ExamId,
                MarksObtained = examresult.MarksObtained,
                Candidate = examresult.Candidate
            };
            return View(viewModel);
        }


        //Save Input Mark
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>  SaveInputMark(InputMarkViewModel viewmodel)
        {
            
            if (ModelState.IsValid)
            {
                if (viewmodel.MarksObtained != null)
                {
                    double doubleValue = (double)viewmodel.MarksObtained;
                    if (doubleValue > 100 || doubleValue < 0)
                    {
                        ModelState.AddModelError("MarksObtained", "The Mark must be between 0 and 100");
                        return View("InputMarks", viewmodel);
                    }
                }

                var resultexam = await _context.ExamResults.Where(er => er.ResultId == viewmodel.ResultId).FirstOrDefaultAsync();

                if (resultexam == null)
                {
                    TempData["message"] = "Cannot find any data";
                    return RedirectToAction("Message", "Dashboard");
                }
                resultexam.MarksObtained = viewmodel.MarksObtained;
                _context.ExamResults.Update(resultexam);

                await _context.SaveChangesAsync();
                return RedirectToAction("ListCandidate", new {id = resultexam.ExamId});
            }
            return View("InputMarks", viewmodel);

        }

        //Enter Mark For Candidate
        //public async Task<IActionResult> EnterMarks(int id)
        //{
        //    var examresult = await _context.ExamResults.Where(e => e.ExamId == id).Select(er => new EnterMarksModel
        //    {
        //        ResultId = er.ResultId,
        //        ExamId = id,
        //        CandidateId = er.CandidateId,
        //        MarksObtained = er.MarksObtained,
        //        Candidate = er.Candidate,
        //        Exam = er.Exam
        //    })
        //    .ToListAsync();

        //    return View(examresult);
        //}
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> SaveMarks(List<EnterMarksModel> viewModel )
        //{
        //    if (ModelState.IsValid)
        //    {
        //        foreach (var result in viewModel)
        //        {
        //            var eachResult = await _context.ExamResults
        //                .Where(er => er.ExamId == result.ExamId && er.CandidateId == result.CandidateId).FirstOrDefaultAsync();

        //            if (eachResult == null)
        //            {
        //                eachResult = new ExamResult
        //                {
        //                    ExamId = result.ExamId,
        //                    CandidateId = result.CandidateId,
        //                    MarksObtained = result.MarksObtained
        //                };
        //                _context.ExamResults.Add(eachResult);
        //            }

ZealEducationManager/Views/Reports/BatchesAboutToEnd.cshtml
@model IEnumerable<ZealEducationManager.Entities.Batch>

@{
    ViewData["Title"] = "Batches About To End";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}
<div class="page-header">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-12">
			<h5 class="text-uppercase mb-0 mt-0 page-title">Batches About To End</h5>
		</div>
	</div>
</div>
<div class="content-page">
	<div class="row">
		<div class="col-md-12 mb-3">
			<div class="table-responsive">
				<table class="table custom-table mb-0 datatable">
					<thead class="thead-light">
						<tr>
							<th>Batch Code </th>
							<th>Start Date</th>
							<th>End Date</th>
							<th class="text-right">Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							<tr class="Batch-completed">
								<td>
									@Html.DisplayFor(modelItem => item.BatchCode)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.StartDate)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.EndDate)
								</td>
								<td class="text-right">
									<div class="dropdown dropdown-action">
										<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
										   aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
										<div class="dropdown-menu dropdown-menu-right">
											<a class="dropdown-item" asp-controller="Batches" asp-action="ListCandidate" asp-route-id="@item.BatchId" title="Detail">
												<i class="fas fa-book m-r-5"></i> Details
											</a>
											<a class="dropdown-item" asp-controller="Batches" asp-action="Edit" asp-route-id="@item.BatchId" title="Edit">
												<i class="fas fa-pencil-alt m-r-5"></i> Edit
											</a>
											<a class="dropdown-item" asp-controller="Batches" asp-action="Delete" asp-route-id="@item.BatchId" title="Delete">
												<i class="fas fa-trash-alt m-r-5"></i> Delete
											</a>
										</div>
									</div>
								</td>
							</tr>
						}

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

ZealEducationManager/Views/Reports/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<div class="page-header">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <h5 class="text-uppercase mb-0 mt-0 page-title">Batches Reports</h5>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <ul class="activity-list">
            <li>
                <a asp-action="BatchesAboutToEnd">Batches Abbout To End</a>
            </li>
            <li>
                <a asp-action="RecentlyStartedBatches">Recently Started Batches</a>
            </li>
            <li>
                <a asp-action="ListBatches">List Candidates In Batch</a>
            </li>
        </ul>
    </div>
</div>


<div class="page-header">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <h5 class="text-uppercase mb-0 mt-0 page-title">Candidates Reports</h5>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <ul class="activity-list">
            <li>
                <a asp-action="MonthYearCandidates" asp-route-month="@DateTime.Now.Month" asp-route-year="@DateTime.Now.Year">List Candidates by Month/Year</a>
            </li>
            <li>
                <a asp-controller="Batches" asp-action="Index">Candidates By Batch</a>
            </li>
            <li>
                <a asp-action="OutstandingFeeCandidates">Candidates With Outstanding Fee</a>
            </li>
        </ul>
    </div>
</div>

<div class="page-header">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <h5 class="text-uppercase mb-0 mt-0 page-title">Exam Reports</h5>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <ul class="activity-list">
            <li>
                <a asp-action="ListBatches">Exams By Batch</a>
            </li>

        </ul>

    </div>
</div>

ZealEducationManager/Views/Reports/ListBatchExams.cshtml
@model IEnumerable<ZealEducationManager.Entities.Exam>

@{
    ViewData["Title"] = "ListBatchExams";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    var batchcode = ViewData["BatchCode"];
}

<div class="page-header">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6 col-12">
            <h5 class="text-uppercase mb-0 mt-0 page-title">Exams in @batchcode </h5>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12 mb-3">
        <div class="table-responsive">
            <table class="table custom-table datatable">
                <thead class="thead-light">
                    <tr>
                        <th>Exam Date</th>
                        <th>Batch </th>
                        <th>Course</th>
                        <th class="text-right">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ExamDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Batch.BatchCode)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Course.CourseCode)
                            </td>
                            <td class="text-right">
                                <a asp-controller="Exams" asp-action="ListCandidate" asp-route-id="@item.ExamId" class="btn btn-primary btn-sm mb-1">
                                    List
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ZealEducationManager/Views/Reports/ListBatches.cshtml
@model IEnumerable<ZealEducationManager.Entities.Batch>

@{
	ViewData["Title"] = "List Batches";
	Layout = "~/Views/Shared/Admin_Layout.cshtml";
}


<div class="page-header">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-12">
			<h5 class="text-uppercase mb-0 mt-0 page-title">List Batches </h5>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12 mb-3">
		<div class="table-responsive">
			<table class="table custom-table mb-0 datatable">
				<thead class="thead-light">
					<tr>
						<th>Batch Code </th>
						<th>Start Date</th>
						<th>End Date</th>
						<th class="text-right">Action</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr class="Batch-completed">
							<td>
								@Html.DisplayFor(modelItem => item.BatchCode)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.StartDate)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.EndDate)
							</td>
							<td class="text-right">
								<a asp-controller="Batches" asp-action="ListCandidate" asp-route-id="@item.BatchId">View Candidates</a> ||
								<a asp-action="ListBatchExams" asp-route-id="@item.BatchId">Exams</a>
							</td>
						</tr>
					}

				</tbody>
			</table>
		</div>
	</div>
</div>
</div>

ZealEducationManager/Views/Reports/MonthYearCandidates.cshtml
@model IEnumerable<ZealEducationManager.Entities.Candidate>
@{
    ViewData["Title"] = "Month Year Canddates";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
    var month = ViewBag.Month;
    var year = ViewBag.Year; 
    int previousMonth = month - 1;
    int previousYear = year;
    if (previousMonth < 1)
    {
        previousMonth = 12;
        previousYear -= 1;
    }

    // Calculate next month and year
    int nextMonth = month + 1;
    int nextYear = year;
    if (nextMonth > 12)
    {
        nextMonth = 1;
        nextYear += 1;
    }

    // Calculate previous and next years
    int yearBefore = year - 1;
    int yearAfter = year + 1;

}

<h2>Candidate Joined in @month/@year</h2>

<table class="table datatable">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date of Joining</th>
            <th>Batch</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var candidate in Model)
        {
            <tr>
                <td>@candidate.FirstName @candidate.LastName</td>
                <td>@candidate.DateOfJoining.ToString("yyyy-MM-dd")</td>
                <td>@candidate.Batch.BatchCode</td>
                <td><a asp-controller="Candidates" asp-action="Details" asp-route-id="@candidate.CandidateId" >View Details</a></td>
            </tr>
        }
    </tbody>
</table>
<hr/>
<div class="text-center">
    <a class="btn btn-outline-primary" asp-action="MonthYearCandidates" asp-route-month="@month" asp-route-year="@yearBefore">Previous Year</a> |
    <a class="btn btn-outline-secondary" asp-action="MonthYearCandidates" asp-route-month="@previousMonth" asp-route-year="@previousYear">Previous Month</a> |
    <a class="btn btn-outline-secondary" asp-action="MonthYearCandidates" asp-route-month="@nextMonth" asp-route-year="@nextYear">Next Month</a> |
    <a class="btn btn-outline-primary" asp-action="MonthYearCandidates" asp-route-month="@month" asp-route-year="@yearAfter">Next Year</a>
</div>

ZealEducationManager/Views/Reports/OutstandingFeeCandidates.cshtml
@model IEnumerable<ZealEducationManager.Entities.Candidate>
@{
    ViewData["Title"] = "OutstandingFeeCandidates";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}


<h1>Candidates With Outstanding Fee</h1>

<table class="table datatable">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Batch
            </th>
            <th>
                Outstanding Fee
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Batch.BatchCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OutstandingFee)
                </td>
                <td>
                    <a asp-controller="Candidates" asp-action="Details" asp-route-id="@item.CandidateId">View Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row">
    <a class="btn btn-secondary" asp-action="Index">Back</a>
</div>

ZealEducationManager/Views/Reports/RecentlyStartedBatches.cshtml
@model IEnumerable<ZealEducationManager.Entities.Batch>
@{
    ViewData["Title"] = "Recently Started Batches";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}


<div class="page-header">
	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-6 col-12">
			<h5 class="text-uppercase mb-0 mt-0 page-title">Recently Started Batches</h5>
		</div>
	</div>
</div>
<div class="content-page">
	<div class="row">
		<div class="col-md-12 mb-3">
			<div class="table-responsive">
				<table class="table custom-table mb-0 datatable">
					<thead class="thead-light">
						<tr>
							<th>Batch Code </th>
							<th>Start Date</th>
							<th>End Date</th>
							<th class="text-right">Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach (var item in Model)
						{
							<tr class="Batch-completed">
								<td>
									@Html.DisplayFor(modelItem => item.BatchCode)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.StartDate)
								</td>
								<td>
									@Html.DisplayFor(modelItem => item.EndDate)
								</td>
								<td class="text-right">
									<div class="dropdown dropdown-action">
										<a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown"
										   aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
										<div class="dropdown-menu dropdown-menu-right">
											<a class="dropdown-item" asp-controller="Batches" asp-action="ListCandidate" asp-route-id="@item.BatchId" title="Detail">
												<i class="fas fa-book m-r-5"></i> Details
											</a>
											<a class="dropdown-item" asp-controller="Batches" asp-action="Edit" asp-route-id="@item.BatchId" title="Edit">
												<i class="fas fa-pencil-alt m-r-5"></i> Edit
											</a>
											<a class="dropdown-item" asp-controller="Batches" asp-action="Delete" asp-route-id="@item.BatchId" title="Delete">
												<i class="fas fa-trash-alt m-r-5"></i> Delete
											</a>
										</div>
									</div>
								</td>
							</tr>
						}

					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>